In [121]:
import numpy as np

In [122]:
#題目：array1 = np.array(range(30))
array1 = np.array(range(30))
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [123]:
#1.將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。
array=array1.reshape(5,6)
print(array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [124]:
#2.呈上題的 array，找出被 6 除餘 1 的數的索引
for i in array:
    print(i % 6==1)
np.where(array % 6==1)

[False  True False False False False]
[False  True False False False False]
[False  True False False False False]
[False  True False False False False]
[False  True False False False False]


(array([0, 1, 2, 3, 4], dtype=int64), array([1, 1, 1, 1, 1], dtype=int64))

In [125]:
#1.將上列陣列(array1)，轉成維度為(5X6)的 array2，順序按列填充。(hint:order="F")
array2=array1.reshape(5,6,order="F")
print(array2)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [126]:
#2.呈上題的 array2，找出被 6 除餘 1 的數的索引
for i in array2:
    print(i % 6==1)
np.where(array2 % 6==1)

[False False False False False  True]
[ True False False False False False]
[False  True False False False False]
[False False  True False False False]
[False False False  True False False]


(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))